#!/bin/sh

dist="/usr/dist"
etcbackup="/usr/etcbackup/"
release="/"

if [ -d "/usr/local/etc/pkg/repos/" ] ; then
  rm -rf /usr/local/etc/pkg/repos/
fi

if [ -f "/usr/local/etc/pkg.conf" ] ; then
  rm /usr/local/etc/pkg.conf
fi

cp -R trueos-repo/ /

if [ ! -d "${dist}" ] ; then
  mkdir ${dist}
fi

if [ ! -d "${etcbackup}" ] ; then
  mkdir ${etcbackup}
fi

cp -R /etc/ ${etcbackup}
cd ${dist}
fetch http://pkg.trueos.org/iso/unstable/base.txz
cd ${dist}
fetch http://pkg.trueos.org/iso/unstable/kernel.txz
cd ${dist}
fetch http://pkg.trueos.org/iso/unstable/lib32.txz


cd ${dist}
chflags -R noschg /
tar -zxvf kernel.txz -C ${release}
tar -zxvf base.txz -C ${release}
tar -zxvf lib32.txz -C ${release}
cp ${etcbackup}master.passwd /etc/master.passwd
cp ${etcbackup}passwd /etc/passwd
cp ${etcbackup}group /etc/group
cp ${etcbackup}*.db /etc/
cp -R ${etcbackup}ssh/ /etc/ssh/
ln -s /etc/init.d/sshd /etc/runlevels/boot/sshd
