#!/bin/sh
dist="/builder/dist"

if [ -d "${dist}" ] ; then
  rm -rf ${dist}
fi

if [ ! -d "${dist}" ] ; then
  mkdir ${dist}
fi

if [ ! -f "${dist}/base.txz" ] ; then 
  cd ${dist}
  fetch http://download.trueos.org/master/amd64/dist/base.txz
fi
if [ ! -f "${dist}/kernel.txz" ] ; then
  cd ${dist}
  fetch http://download.trueos.org/master/amd64/dist/kernel.txz
fi
