#!/bin/sh
dist="/builder/root-fbsd12-amd64"
tmpdist="/root/tmpdist"

if [ -d "${tmptist}" ] ; then
  rm -rf ${tmptist}
fi

if [ ! -d "${tmptist}" ] ; then
  mkdir ${tmptist}
fi

if [ ! -f "${tmptist}/base.txz" ] ; then 
  cd ${tmptist}
  fetch http://download.trueos.org/master/amd64/tmptist/base.txz
fi
if [ ! -f "${tmptist}/kernel.txz" ] ; then
  cd ${tmptist}
  fetch http://download.trueos.org/master/amd64/tmptist/kernel.txz
fi

if [ ! -f "${tmpdist}/base.txz" ] ; then 
  cd ${tmpdist}
  fetch http://download.trueos.org/master/amd64/dist/base.txz
fi
if [ ! -f "${tmpdist}/kernel.txz" ] ; then
  cd ${tmpdist}
  fetch http://download.trueos.org/master/amd64/dist/kernel.txz
fi
