#!/bin/sh
base="/builder/root-fbsd12-amd64"
dist="/root/dist"

if [ -d "${dist}" ] ; then
  rm -rf ${dist}
fi

if [ ! -d "${dist}" ] ; then
  mkdir ${dist}
fi

cd ${dist}
fetch http://pkg.trueos.org/iso/unstable/base.txz
fetch http://pkg.trueos.org/iso/unstable/kernel.txz
fetch http://pkg.trueos.org/iso/unstable/lib32.txz
fetch http://pkg.trueos.org/iso/unstable/src.txz

rm -rf ${base}/

tar -zxvf base.txz -C ${base}
tar -zxvf kernel.txz -C ${base}
tar -zxvf lib32.txz -C ${base}
tar -zxvf src.txz -C ${base}
