#!/bin/sh
base="/builder/root-fbsd12-amd64"
dist="/root/dist"

if [ -d "${dist}" ] ; then
  rm -rf ${dist}
fi

if [ ! -d "${dist}" ] ; then
  mkdir ${dist}
fi

cd ${dist}
fetch http://download.trueos.org/master/amd64/dist/base.txz
fetch http://download.trueos.org/master/amd64/dist/kernel.txz
fetch http://download.trueos.org/master/amd64/dist/lib32.txz
fetch http://download.trueos.org/master/amd64/dist/src.txz

tar -zxvf kernel.txz -C ${base}
tar -zxvf base.txz -C ${base}
tar -zxvf lib32.txz -C ${base}
tar -zxvf src.txz -C ${base}
